import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ConvexClientProvider } from "./ConvexClientProvider";
import { Toaster } from "@/components/ui/sonner";
import { Footer } from "@/components/Layout/Footer";
import { ConvexAuthNextjsServerProvider } from "@convex-dev/auth/nextjs/server";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Darviz",
  description: "Generated by Gatekeepr",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ConvexAuthNextjsServerProvider>
      <html lang="en">
        <head>
          <script
            defer
            src="https://cloud.umami.is/script.js"
            data-website-id="1442dd42-4103-4470-a40f-05ed5a742c45"
          ></script>
        </head>
        <body
          className={`${geistSans.variable} ${geistMono.variable} relative antialiased`}
        >
          <ConvexClientProvider>{children}</ConvexClientProvider>
          <Toaster />
          {/* Footer */}
          <Footer />
        </body>
      </html>
    </ConvexAuthNextjsServerProvider>
  );
}
